services:

  dbmaster:
    image: mysql:8.0
    container_name: dbmaster1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chatapp
    networks:
      - mysql-network
      - app-network
    ports:
      - "3306:3306"
    command: --server-id=1 --log-bin=mysql-bin --binlog-do-db=testdb

  dbreplica:
    image: mysql:8.0
    container_name: dbreplica1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chatapp
    networks:
      - mysql-network
    command: --server-id=2 --log-bin=mysql-bin --binlog-do-db=testdb

  phpmyadmin1:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin1
    environment:
      PMA_HOST: dbmaster
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - mysql-network
    ports:
      - "8081:80"

  phpmyadmin2:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin2
    environment:
      PMA_HOST:  dbreplica
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - mysql-network
    ports:
      - "8082:80"

  app1:  # Instancia 1 de la app
    container_name: app1
    build: .
    environment:
      - MYSQL_HOST=dbmaster
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=chatapp
      - MYSQL_PORT=3306
    networks:
      - app-network

  app2:  # Instancia 2 de la app
    container_name: app2
    build: .
    environment:
      - MYSQL_HOST=dbmaster
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=chatapp
      - MYSQL_PORT=3306
    networks:
      - app-network

  nginx_server:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8084:80"
    networks:
      - app-network
    depends_on:
      - app1
      - app2
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf


networks:
  mysql-network:
    driver: bridge
  app-network:
    driver: bridge
