services:
  # Contenedor de la base de datos (MySQL)
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: instamessage_db
    ports:
      - "3306:3306"
    volumes:
      - bkpDB:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 20s
      retries: 10

    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  # Contenedor para la vista de la base de datos (PHPMyAdmin)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql-db
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    depends_on:
      mysql-db:
        condition: service_healthy
  
volumes:
  bkpDB: